# Имя пакета, который мы ищем
package_name = "python3-toml"

# Режим работы: 'remote' или 'local'
working_mode = "local" # 'remote' - качает из сети, 'local' - читает с диска

# --- Параметры для 'remote' режима ---
# Базовый URL репозитория
repository_url = "Packages (2).gz"
distribution = "jammy" # (Ubuntu 22.04)
# Компонент (main, universe, restricted, multiverse)
component = "universe"
architecture = "amd64"
max_depth = 5
filter_substring = ""